# Generated by Django 4.2.3 on 2023-09-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sold_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isdiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
