# Generated by Django 4.2.3 on 2023-09-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product02.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(blank=True, default='product02.png', null=True),
        ),
    ]
