# Generated by Django 4.2.3 on 2023-09-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image_alter_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='pc.png', null=True, upload_to=''),
        ),
    ]
