# Generated by Django 4.2.3 on 2023-09-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/pc.png', null=True, upload_to=''),
        ),
    ]
