# Generated by Django 4.2.3 on 2023-09-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_email_remove_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=16),
        ),
    ]
