# Generated by Django 4.2.3 on 2023-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_complete_alter_order_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
