# Generated by Django 4.2.3 on 2023-09-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_first_name_product_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
