# Generated by Django 4.2.3 on 2023-09-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_first_name_remove_product_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
